logging:
  level:
    com.zhangyun.portalknight.server: info
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
